baseline: Updates from CTP
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
description: Updates by CTP's communications.
date:
  format: j F Y
  timezone: Europe/Paris
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: CTP Ethiopia News
baseurl: /
canonicalurl: true
